version: 2
jobs:
  deploy:
    machine:
      enable: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "19:08:6e:9a:11:1e:92:23:29:55:9d:67:54:c8:aa:08"
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "cd ~/Medici; git pull origin master;"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master