drop table if exists `COM_ARTIST_PIVATE_INFO_MST`;
CREATE TABLE `MEDICI`.`COM_ARTIST_PIVATE_INFO_MST` (
  `ARTIST_PRIVATE_ID` BIGINT NOT NULL,
  `ARTIST_ID` BIGINT NOT NULL,
  `PHONE_NUMBER` INT,
  `MAIL_ADDRESS` VARCHAR(256),
  `POSTAL_CODE` VARCHAR(50),
  `ADDRESS` VARCHAR(300),
  `WORK_PLACE_POSTAL_CODE` VARCHAR(50),
  `WORK_PLACE_ADDRESS` VARCHAR(300),
  `FORMAL_NAME` VARCHAR(200),
  PRIMARY KEY(`ARTIST_PRIVATE_ID`, `ARTIST_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

drop table if exists `ART_WORK_MST`;
CREATE TABLE MEDICI.ART_WORK_MST (
  WORK_ID BIGINT NOT NULL PRIMARY KEY,
  ARTIST_ID BIGINT NOT NULL,
  START_DATE DATE NOT NULL,
  END_DATE DATE NOT NULL,
  WORK_TITLE_JA VARCHAR(200),
  WORK_TITLE_EN VARCHAR(200),
  WORK_DESCRIPTION_JA BLOB,
  WORK_DESCRIPTION_EN BLOB,
  WORK_IMAGE_PATH VARCHAR(200),
  CREATE_YEAR INT,
  SIZE VARCHAR(100),
  SIZE_X_POSITION INT,
  SIZE_Y_POSITION INT,
  SIZE_Z_POSITION INT,
  MATERIAL VARCHAR(200)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

drop table if exists `ART_RELETED_ITEM_MST`;
CREATE TABLE MEDICI.ART_RELETED_ITEM_MST (
  ITEM_ID BIGINT NOT NULL PRIMARY KEY,
  ARTIST_ID BIGINT NOT NULL,
  START_DATE DATE NOT NULL,
  END_DATE DATE NOT NULL,
  ITEM_NAME_JA VARCHAR(200),
  ITEM_NAME_EN VARCHAR(200),
  ITEM_DESCRIPTION_JA BLOB,
  ITEM_DESCRIPTION_EN BLOB,
  ITEM_IMAGE_PATH VARCHAR(200),
  SIZE VARCHAR(100),
  SIZE_X_POSITION INT,
  SIZE_Y_POSITION INT,
  SIZE_Z_POSITION INT,
  MATERIAL VARCHAR(200)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

drop table if exists `ART_ARTIST_EVENT_TRN`;
CREATE TABLE `ART_ARTIST_EVENT_TRN` (
  `EVENT_ID` bigint(20) NOT NULL,
  `ARTIST_ID` bigint(20) NOT NULL,
  `START_DATE` date NOT NULL,
  `END_DATE` date NOT NULL,
  `EVENT_NAME_JA` varchar(200) DEFAULT NULL,
  `EVENT_NAME_EN` varchar(200) DEFAULT NULL,
  `EVENT_DESCRIPTION_JA` blob,
  `EVENT_DESCRIPTION_EN` blob,
  `EVENT_IMAGE_PATH` varchar(200) DEFAULT NULL,
  `EVENT_START_AT` datetime NULL DEFAULT NULL,
  `EVENT_END_AT` datetime NULL DEFAULT NULL,
  `EVENT_PHONE` int(11) DEFAULT NULL,
  `EVENT_MAIL_ADDRESS` varchar(256) DEFAULT NULL,
  `EVENT_URL` blob,
  PRIMARY KEY (`EVENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

drop table if exists `ART_MEDIA_TRN`;
CREATE TABLE MEDICI.ART_MEDIA_TRN (
  MEDIA_ID BIGINT NOT NULL PRIMARY KEY,
  ARTIST_ID BIGINT NOT NULL,
  START_DATE DATE NOT NULL,
  END_DATE DATE NOT NULL,
  MEDIA1_TYPE INT,
  MEDIA_NAME_JA VARCHAR(200),
  MEDIA_NAME_ VARCHAR(200),
  MEDIA_DESCRIPTION_JA BLOB,
  MEDIA_DESCRIPTION_EN BLOB,
  MEDIA_URL BLOB
) ENGINE=InnoDB DEFAULT CHARSET=utf8;